# Generated by Django 2.2 on 2022-01-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishmgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
