# Generated by Django 2.2 on 2022-01-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishmgt', '0002_auto_20220129_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
